### ISSUE TITLE
Windows error running python start.py

### ISSUE THREAD

**Issue by ahmaddxb** [ZkSnow/ScryConnect#2]
python start.py
Traceback (most recent call last):
  File "C:\Users\ahaghshenas\Downloads\ScryConnect-main\ScryConnect-main\start.py", line 8, in <module>
    from UI.ClientUI import Client
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahaghshenas\Downloads\ScryConnect-main\ScryConnect-main\UI\ClientUI.py", line 11, in <module>
    from UI.Tabs.ConnectTabUI import ConnectTab
  File "C:\Users\ahaghshenas\Downloads\ScryConnect-main\ScryConnect-main\UI\Tabs\ConnectTabUI.py", line 4, in <module>
    from UI.DeviceListUI import DeviceListUI
  File "C:\Users\ahaghshenas\Downloads\ScryConnect-main\ScryConnect-main\UI\DeviceListUI.py", line 5, in <module>
    from Script.ConnectTAB_Functions import DeviceList
  File "C:\Users\ahaghshenas\Downloads\ScryConnect-main\ScryConnect-main\Script\ConnectTAB_Functions.py", line 5, in <module>
    from UI.DeviceSelection import DeviceSelectionUI
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahaghshenas\Downloads\ScryConnect-main\ScryConnect-main\UI\DeviceSelection.py", line 18, in <module>
    from Script.Thread_Config_Tab import ConfigTAB_Thread
  File "C:\Users\ahaghshenas\Downloads\ScryConnect-main\ScryConnect-main\Script\Thread_Config_Tab.py", line 1, in <module>
    from curses.ascii import isdigit
  File "C:\Users\ahaghshenas\AppData\Local\Programs\Python\Python312\Lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

to fix i had too run pip install windows-curses, maybe include that in the requirements

**Comment by ZkSnow** [comment]
Oh, that was something I didn't realize, probably because the freeze didn't detect it or something, now it's there in the README, thanks!
